codecov:
  require_ci_to_pass: false

coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
        # Allow decreasing 2% of total coverage to avoid noise.
        threshold: 2%
        if_ci_failed: error
        informational: true
        branches:
          - main
        paths:
          - "src"
          - "pkg"
          - "!*/mocks"
          - "!*/testutils"
    patch:
      default:
        target: 90%
        threshold: 0%
        informational: true
        branches:
          - main
        paths:
          - "src"
          - "pkg"
          - "cmd"
          - "!*/mocks"
          - "!*/testutils"
      
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  
ignore:
  - main.go
  - "*/testutils"
  - "*/mocks"
