---
version: 2.1

orbs:
  codecov: codecov/codecov@3.2
  
executors:
  golang_executor:
    docker:
      - image: circleci/golang:1.15

commands:
  prepare_golang:
    description: "checkout, install all packages and handle cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Set Git URL rewrite
          command: |
            git config --global --add url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
            git config --global --add url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
      - run:
          name: Pull and build dependencies for the project
          command: go get
      - run:
          name: Install binary compresor
          command: |
            sudo apt update
            sudo apt -y install upx-ucl
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  prepare_docker:
    description: "Docker login"
    steps:
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            echo $DOCKER_PASS_2 | docker login -u $DOCKER_USER_2 --password-stdin $DOCKER_REGISTRY_2

  docker_build_image:
    description: "Build Quorum Hashicorp Vault Plugin docker image"
    steps:
      - run:
          name: Build Quorum Hashicorp Vault Plugin
          command: >-
            DOCKER_BUILDKIT=1 docker build
            --label org.opencontainers.image.created=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
            --label org.opencontainers.image.url="https://consensys.net"
            --label org.opencontainers.image.documentation="https://docs.quorum-key-manager.consensys.net/"
            --label org.opencontainers.image.source="${CIRCLE_REPOSITORY_URL}"
            --label org.opencontainers.image.version="${CIRCLE_TAG}"
            --label org.opencontainers.image.revision="${CIRCLE_SHA1:0:7}"
            --label org.opencontainers.image.vendor="ConsenSys Software Inc."
            --label org.opencontainers.image.licenses="BUSL-1.1"
            --label org.opencontainers.image.title="${CIRCLE_PROJECT_REPONAME}"
            --label org.opencontainers.image.description="This Quorum plugin enhances Hashicorp Vault Service with cryptographic operations under Vault engine."
            -q
            -t quorum-hashicorp-vault-plugin:${CIRCLE_SHA1:0:7} .

jobs:
  styleCheck:
    executor: golang_executor
    steps:
      - prepare_golang
      - run:
          name: Install linting tools
          command: make lint-tools
      - run:
          name: Check lints
          command: make lint-ci

  build:
    executor: golang_executor
    steps:
      - prepare_golang
      - run:
          name: Build
          command: |
            CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -a -v -o build/bin/quorum-hashicorp-vault-plugin
            upx build/bin/quorum-hashicorp-vault-plugin
            sha256sum -b build/bin/quorum-hashicorp-vault-plugin | cut -d' ' -f1 > build/bin/SHA256SUM
      - persist_to_workspace:
          root: ~/project/build/bin
          paths:
            - ./
  test:
    executor: golang_executor
    steps:
      - prepare_golang
      - run:
          name: Unit tests
          command: make run-coverage
      - codecov/upload:
          file: ./build/coverage/coverage.out
      - store_artifacts:
          path: ./build/coverage/coverage.html
          destination: coverage.html

  publish-github-release:
    executor: golang_executor
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION="${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

  push-dev-image:
    docker:
      - image: cimg/base:2020.01
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - prepare_docker
      - docker_build_image
      - run:
          name: Deploy image in repository
          command: |
            docker tag quorum-hashicorp-vault-plugin:${CIRCLE_SHA1:0:7} ${DOCKER_REGISTRY_DEV_REPO}/quorum-hashicorp-vault-plugin:${CIRCLE_SHA1:0:7}
            docker push ${DOCKER_REGISTRY_DEV_REPO}/quorum-hashicorp-vault-plugin:${CIRCLE_SHA1:0:7}
            
            docker tag quorum-hashicorp-vault-plugin:${CIRCLE_SHA1:0:7} ${DOCKER_REGISTRY_DEV_REPO}/quorum-hashicorp-vault-plugin:develop
            docker push ${DOCKER_REGISTRY_DEV_REPO}/quorum-hashicorp-vault-plugin:develop

  push-prod-image:
    docker:
      - image: cimg/base:2020.01
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - prepare_docker
      - docker_build_image
      - run:
          name: Deploy image in repository
          command: |
            docker tag quorum-hashicorp-vault-plugin:${CIRCLE_SHA1:0:7} ${DOCKER_REGISTRY_REPO_2}/quorum-hashicorp-vault-plugin:${CIRCLE_TAG}
            docker push ${DOCKER_REGISTRY_REPO_2}/quorum-hashicorp-vault-plugin:${CIRCLE_TAG}

            docker tag quorum-hashicorp-vault-plugin:${CIRCLE_SHA1:0:7} ${DOCKER_REGISTRY_REPO_2}/quorum-hashicorp-vault-plugin:latest
            docker push ${DOCKER_REGISTRY_REPO_2}/quorum-hashicorp-vault-plugin:latest
            
workflows:
  version: 2
  default:
    jobs:
      - styleCheck:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - push-dev-image:
          filters:
            branches:
              only: main
          requires:
            - styleCheck
            - test
            - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - push-prod-image:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - publish-github-release
